#!/usr/bin/env python3
"""Generate test/test_golden_generated.cpp from the PYTHON SDK.

This is the port's parity harness. Rather than hand-copying expected values
(which is how a port drifts), it drives the real Python implementation and
emits the exact bytes it produces; the C++ test then has to reproduce them.

Deterministic: fixed seed, so regenerating without changing the Python SDK
produces a byte-identical file.

Usage (from litegrip_cpp/):

    python3 test/generate_golden.py
"""

from __future__ import annotations

import os
import random
import struct
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SDK_ROOT = os.path.normpath(os.path.join(HERE, "..", "..", "litegrip_driver"))
sys.path.insert(0, SDK_ROOT)

from litegrip.can import protocol as P  # noqa: E402

SEED = 20260928
N_QUANT = 64
N_MIT = 64
N_STATUS = 64
N_WRITE = 48
N_PARAM_RESP = 48

# Motor limits to exercise: DM4310 (default), DM4340, DM6248P.
LIMIT_SETS = [
    (1, P.get_motor_limits(1)),
    (3, P.get_motor_limits(3)),
    (6, P.get_motor_limits(6)),
]


def c_double(value: float) -> str:
    """Emit a double literal that round-trips exactly."""
    return repr(float(value))


def bytes_c(values) -> str:
    return "{" + ", ".join(f"0x{b:02X}" for b in values) + "}"


def main() -> int:
    rng = random.Random(SEED)
    out: list[str] = []

    out.append("// AUTO-GENERATED by test/generate_golden.py — DO NOT EDIT.")
    out.append("//")
    out.append("// Values are produced by the Python SDK (litegrip_driver) and must be")
    out.append("// reproduced byte-for-byte by the C++ port. Regenerate with:")
    out.append("//     python3 test/generate_golden.py")
    out.append("")
    out.append('#include "litegrip/can/protocol.hpp"')
    out.append("")
    out.append("namespace litegrip::test::golden {")
    out.append("")

    # ── quantization round-trips ──────────────────────────────────────────
    out.append("struct QuantVector {")
    out.append("  double value, value_min, value_max;")
    out.append("  int bits;")
    out.append("  unsigned int encoded;")
    out.append("  double decoded;")
    out.append("};")
    out.append("")
    out.append("constexpr QuantVector kQuantVectors[] = {")
    probes = [(-999.0, -12.5, 12.5, 16), (999.0, -12.5, 12.5, 16),
              (0.0, -12.5, 12.5, 16), (6.25, -12.5, 12.5, 16),
              (-6.25, -12.5, 12.5, 16), (12.5, -12.5, 12.5, 16),
              (-12.5, -12.5, 12.5, 16), (0.0, 0.0, 500.0, 12),
              (250.0, 0.0, 500.0, 12), (500.0, 0.0, 500.0, 12),
              (0.0, 0.0, 5.0, 12), (5.0, 0.0, 5.0, 12),
              (0.0, -30.0, 30.0, 12), (30.0, -30.0, 30.0, 12),
              (-30.0, -30.0, 30.0, 12), (0.0, -10.0, 10.0, 12)]
    for _ in range(N_QUANT):
        bits = rng.choice([12, 16])
        lo = rng.choice([-12.5, -30.0, -10.0, 0.0])
        hi = rng.choice([5.0, 10.0, 12.5, 30.0, 500.0])
        if hi <= lo:
            hi = lo + 1.0
        probes.append((rng.uniform(lo * 1.2, hi * 1.2), lo, hi, bits))

    for value, lo, hi, bits in probes:
        encoded = P.float_to_uint(value, lo, hi, bits)
        decoded = P.uint_to_float(encoded, lo, hi, bits)
        out.append(f"    {{{c_double(value)}, {c_double(lo)}, {c_double(hi)}, "
                   f"{bits}, {encoded}u, {c_double(decoded)}}},")
    out.append("};")
    out.append("")

    # ── MIT frames ────────────────────────────────────────────────────────
    out.append("struct MitVector {")
    out.append("  double q, dq, kp, kd, tau;")
    out.append("  double q_max, dq_max, tau_max;")
    out.append("  unsigned char bytes[8];")
    out.append("};")
    out.append("")
    out.append("constexpr MitVector kMitVectors[] = {")
    for _ in range(N_MIT):
        _, limits = rng.choice(LIMIT_SETS)
        q = rng.uniform(-limits.q_max, limits.q_max)
        dq = rng.uniform(-limits.dq_max, limits.dq_max)
        kp = rng.uniform(0.0, 500.0)
        kd = rng.uniform(0.0, 5.0)
        tau = rng.uniform(-limits.tau_max, limits.tau_max)
        data = P.pack_mit_frame(q, dq, kp, kd, tau, q_max=limits.q_max,
                                dq_max=limits.dq_max, tau_max=limits.tau_max)
        out.append(f"    {{{c_double(q)}, {c_double(dq)}, {c_double(kp)}, "
                   f"{c_double(kd)}, {c_double(tau)}, {c_double(limits.q_max)}, "
                   f"{c_double(limits.dq_max)}, {c_double(limits.tau_max)}, "
                   f"{bytes_c(data)}}},")
    out.append("};")
    out.append("")

    # ── status frames ─────────────────────────────────────────────────────
    out.append("struct StatusVector {")
    out.append("  unsigned char raw[8];")
    out.append("  double q_max, dq_max, tau_max;")
    out.append("  int err, can_id, t_mos, t_coil;")
    out.append("  double q, dq, tau;")
    out.append("};")
    out.append("")
    out.append("constexpr StatusVector kStatusVectors[] = {")
    for _ in range(N_STATUS):
        _, limits = rng.choice(LIMIT_SETS)
        raw = bytes(rng.randrange(256) for _ in range(8))
        s = P.unpack_status_frame(raw, q_max=limits.q_max, dq_max=limits.dq_max,
                                  tau_max=limits.tau_max)
        out.append(f"    {{{bytes_c(raw)}, {c_double(limits.q_max)}, "
                   f"{c_double(limits.dq_max)}, {c_double(limits.tau_max)}, "
                   f"{s.err}, {s.can_id}, {s.t_mos}, {s.t_coil}, "
                   f"{c_double(s.q)}, {c_double(s.dq)}, {c_double(s.tau)}}},")
    out.append("};")
    out.append("")

    # ── parameter writes (float + int registers) ──────────────────────────
    out.append("struct WriteVector {")
    out.append("  int can_id, rid;")
    out.append("  double value;")
    out.append("  unsigned char bytes[8];")
    out.append("};")
    out.append("")
    out.append("constexpr WriteVector kWriteVectors[] = {")
    int_regs = [7, 8, 9, 10, 13, 14, 15, 16, 35, 36]
    float_regs = [0, 1, 2, 3, 4, 5, 6, 11, 12, 17, 21, 22, 23, 25, 26]
    for _ in range(N_WRITE):
        can_id = rng.choice([0x08, 0x01, 0x0F])
        if rng.random() < 0.5:
            rid = rng.choice(int_regs)
            value = float(rng.randrange(0, 256))
        else:
            rid = rng.choice(float_regs)
            value = rng.uniform(-100.0, 500.0)
        data = P.pack_write_param_frame(can_id, rid, value)
        out.append(f"    {{{can_id}, {rid}, {c_double(value)}, {bytes_c(data)}}},")
    out.append("};")
    out.append("")

    # ── parameter responses ───────────────────────────────────────────────
    out.append("struct ParamRespVector {")
    out.append("  unsigned char raw[8];")
    out.append("  bool has_value;")
    out.append("  int can_id, opcode, rid;")
    out.append("  double value;")
    out.append("};")
    out.append("")
    out.append("constexpr ParamRespVector kParamRespVectors[] = {")
    for _ in range(N_PARAM_RESP):
        can_id = rng.choice([0x08, 0x01, 0x0E])
        opcode = rng.choice([0x33, 0x55, 0xAA])
        if rng.random() < 0.5:
            rid = rng.choice(int_regs)
            payload = rng.randrange(0, 1 << 24).to_bytes(4, "little")
        else:
            rid = rng.choice(float_regs)
            payload = struct.pack("<f", rng.uniform(-500.0, 500.0))
        raw = bytes([can_id, 0x00, opcode, rid]) + payload
        r = P.unpack_param_response(raw)
        if r is None:
            out.append(f"    {{{bytes_c(raw)}, false, 0, 0, 0, 0.0}},")
        else:
            out.append(f"    {{{bytes_c(raw)}, true, {r.can_id}, {r.opcode}, "
                       f"{r.rid}, {c_double(r.value)}}},")
    out.append("};")
    out.append("")

    # ── fixed frames + decode edge cases ──────────────────────────────────
    out.append("struct ByteFrame {")
    out.append("  int can_id;")
    out.append("  unsigned char bytes[8];")
    out.append("  int size;")
    out.append("};")
    out.append("")
    out.append("constexpr ByteFrame kReadVectors[] = {")
    for can_id in (0x08, 0x01, 0x0F):
        for rid in (int_regs[0], float_regs[-1]):
            data = P.pack_read_param_frame(can_id, rid)
            out.append(f"    {{{can_id}, {bytes_c(data)}, 8}},")
    out.append("};")
    out.append("")
    out.append("constexpr ByteFrame kRefreshVectors[] = {")
    for can_id in (0x08, 0x01, 0x0F):
        data = P.pack_refresh_frame(can_id)
        out.append(f"    {{{can_id}, {bytes_c(data)}, 4}},")
    out.append("};")
    out.append("")
    out.append("constexpr ByteFrame kSaveVectors[] = {")
    for can_id in (0x08, 0x01, 0x0F):
        data = P.pack_save_param_frame(can_id)
        out.append(f"    {{{can_id}, {bytes_c(data)}, 8}},")
    out.append("};")
    out.append("")
    out.append("struct CommandVector {")
    out.append("  unsigned char cmd;")
    out.append("  unsigned char bytes[8];")
    out.append("};")
    out.append("")
    out.append("constexpr CommandVector kCommandVectors[] = {")
    for name, cmd in (("CMD_ENABLE", P.CMD_ENABLE), ("CMD_DISABLE", P.CMD_DISABLE),
                      ("CMD_CLEAR_FAULT", P.CMD_CLEAR_FAULT),
                      ("CMD_SET_ZERO", P.CMD_SET_ZERO)):
        data = P.pack_command_frame(cmd)
        out.append(f"    {{0x{cmd:02X}, {bytes_c(data)}}},  // {name}")
    out.append("};")
    out.append("")
    out.append("}  // namespace litegrip::test::golden")
    out.append("")

    target = os.path.join(HERE, "golden_generated.hpp")
    with open(target, "w", encoding="utf-8") as handle:
        handle.write("\n".join(out))

    counts = {
        "quant": len(probes),
        "mit": N_MIT,
        "status": N_STATUS,
        "write": N_WRITE,
        "param_resp": N_PARAM_RESP,
    }
    print(f"wrote {target}: {counts}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
